# Generated by Django 2.1.5 on 2019-02-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=15)),
                ('sname', models.CharField(max_length=30)),
                ('scourse', models.CharField(max_length=15)),
                ('ssem', models.IntegerField()),
                ('sphn', models.BigIntegerField()),
            ],
        ),
    ]
