# Generated by Django 2.1.7 on 2019-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0002_auto_20190221_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
