# Generated by Django 2.1.7 on 2019-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0003_auto_20190221_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('bcontent', models.CharField(max_length=30)),
                ('bauthor', models.CharField(max_length=30)),
                ('brackno', models.IntegerField()),
            ],
        ),
    ]
