# Generated by Django 2.1.7 on 2019-02-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('bcdate', models.DateField()),
                ('bfine', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminview.Book')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sfine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminview.Student'),
        ),
    ]
