# Generated by Django 2.1.7 on 2019-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0005_auto_20190222_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='bfine',
            field=models.IntegerField(default=0),
        ),
    ]
