# Generated by Django 2.1.7 on 2019-02-23 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0006_auto_20190222_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 23)),
        ),
    ]
