# Generated by Django 2.1.7 on 2019-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0007_services_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
