# Generated by Django 2.1.7 on 2019-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0008_auto_20190223_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='bfine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sfine',
            field=models.FloatField(default=0),
        ),
    ]
